### ISSUE TITLE
[Assignment 1] Review

### ISSUE THREAD

**Issue by minhchau273** [HienQTran/MovieApp#1]
Hi @BallsSqueezer 

Your app crashes immediately when I run at the first time. Please double check and let me know when you complete.  
<img width="760" alt="screen shot 2016-07-12 at 2 59 59 pm" src="https://cloud.githubusercontent.com/assets/12395213/16759508/7b59b180-4841-11e6-807d-77cce86dd7e8.png">

-Chau

**Comment by minhchau273** [comment]
:+1: What an awesome submission! 🌟 😍 I really really enjoy your walkthrough. You are getting so much done! 🚀 The point of this homework was to explore a simple example of a full MVC application with a RESTful API. You learned about UITableViews, custom UITableViewCells, navigation from a UITableView, and basic networking.

## Grading Summary:
* **Functionality**: Outstanding
* **Code Style**: Good
* **Visual Design**: Outstanding

#### **Overall**: Outstanding


## Detailed Notes

* Great clean code. Good job utilizing the best parts from the style guide:
   - [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
* Nice work implementing the `Movie` model.
* Your custom Movie cell should have a property called `movie`. In the custom setter of `movie`, you should configure the various labels and images. This decouples your custom cells from the table view controllers.
* Note that your images are stretched. You should observe the `UIContentMode` of the `UIImageView`. By default, it will stretch the image to match your dimensions, which is probably not what you want.
* Nice work implementing the error message on network failure. However, you have to create your own error message instead of using the alert controller. We mentioned it in the requirements. (`You may not use UIAlertController or a 3rd party library to display the error.`).
* Nice job implementing a `UIScrollView`. `UIScrollView` is the parent class of `UITableView`.
* Nice job keeping things nice and aligned on a grid. That helps the application look cleaner and make it easier for the user to find the correct information. For a lot more information, you can read [Design tips for iOS9](https://designcode.io/iosdesign-guidelines). 
* Great work with the search bar. But there's an issue here. When I search `Do`, your app gives me the `Finding Dory` 6 times. After I pull to refresh and search again, it gives me 7 times.  
![simulator screen shot jul 13 2016 9 51 49 am](https://cloud.githubusercontent.com/assets/12395213/16790415/e3f7a000-48df-11e6-8c92-cea9e7774e64.png)
* I love your `batman`. 😈 
* Nice to show more information in Details screen. It'd be better if you made the text darker. It's a little bit hard to read now.
* It's not a big deal but in case there is no result, you should show a label `No results found` to make your app more friendly :wink:
* I don't remember exactly what I did on your app (around the search bar and grid button) but suddenly your app show a black screen and I cannot tap anything on that though your app doesn't crash).  
![simulator screen shot jul 13 2016 9 54 17 am](https://cloud.githubusercontent.com/assets/12395213/16790579/48f47ed2-48e1-11e6-8026-79b3ca846183.png)


Excellent submission overall 💯 Great job dedicating enough time to do the homework. You learned a lot! Keep up the good work. 🏇

**Comment by BallsSqueezer** [comment]
Thanks for the detail feedback Chau, I would love to show more information about the movie, but in the url provided, there's is not much to show :). I really appreciate you time and effort looking at my not-so-organized code :D. What a mess! 

- I kind of figure out where the problem with the search bar comes from. SILLY Xcode :(. I'll work on those errors and get back to you real soon. 

- And about the last error, so from your experience, in a similar situation when Xcode doesn't complain but something still goes horribly wrong, how can you trace back to the root cause of this kind of problem

**Comment by minhchau273** [comment]
Try to re-construct the issue. When you've already known how to do, add break points in your code where the bug happens. :D
